-- 정책·자격 화면 순서 고정 — 순번 칸 seq(2026-10-06 · 우편함 「코드 — Z-1 ③ …」 0번 · claude.ai 판정 (가)).
--   announcement_policies · eligibility_criteria 의 id 는 gen_random_uuid() 라 순서 키가 못 되고, created_at 은 now()(트랜잭션 시작)라 한 분석 회차 안은 동순위다.
--   화면은 order=category(자격 supply_form,rank)의 동순위를 DB 정렬이 내주는 대로 보였다 — 원문 순서도 아니고 데이터 정리(UPDATE·VACUUM FULL)에도 흔들린다.
--   seq = 들어간 순서. 지금 행은 (created_at, ctid) 순으로 한 번 채운다(분석 회차 순 · 회차 안은 물리 순서 ≈ 분석이 원문을 옮긴 순서) ·
--   새 행은 identity 가 들어간 순서대로 늘린다(분석 스킬은 원문 순서로 INSERT 한다). UPDATE 는 seq 를 건드리지 않는다(Z-1 ③ 이전 포함).
--   화면: order=category,seq · supply_form,rank,seq(index.html 같은 PR).
--   되돌리기: alter table … alter column seq drop identity; alter table … drop column seq(둘) + 화면 order 되돌림.
ALTER TABLE public.announcement_policies ADD COLUMN seq bigint;
ALTER TABLE public.eligibility_criteria ADD COLUMN seq bigint;

UPDATE public.announcement_policies p SET seq = o.n
  FROM (SELECT id, row_number() OVER (ORDER BY created_at, ctid) AS n FROM public.announcement_policies) o
 WHERE o.id = p.id;
UPDATE public.eligibility_criteria e SET seq = o.n
  FROM (SELECT id, row_number() OVER (ORDER BY created_at, ctid) AS n FROM public.eligibility_criteria) o
 WHERE o.id = e.id;

ALTER TABLE public.announcement_policies ALTER COLUMN seq SET NOT NULL;
ALTER TABLE public.eligibility_criteria ALTER COLUMN seq SET NOT NULL;
ALTER TABLE public.announcement_policies ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.eligibility_criteria ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public.announcement_policies', 'seq'), (SELECT max(seq) FROM public.announcement_policies));
SELECT setval(pg_get_serial_sequence('public.eligibility_criteria', 'seq'), (SELECT max(seq) FROM public.eligibility_criteria));

COMMENT ON COLUMN public.announcement_policies.seq IS '들어간 순서(화면 같은 분류 안 순서 = 원문 순서) — 2026-10-06 이전 행은 (created_at, ctid) 순으로 채움 · 새 행은 identity.';
COMMENT ON COLUMN public.eligibility_criteria.seq IS '들어간 순서(화면 같은 공급형·순위 안 순서) — 2026-10-06 이전 행은 (created_at, ctid) 순으로 채움 · 새 행은 identity.';
